// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSTyYVr9OHo7btLXyDRgu5CcbsZ3b24JA',
    appId: '1:232894128071:web:c60c294f52afcf669243e2',
    messagingSenderId: '232894128071',
    projectId: 'myapp-afa3a',
    authDomain: 'myapp-afa3a.firebaseapp.com',
    storageBucket: 'myapp-afa3a.firebasestorage.app',
    measurementId: 'G-8MLJC12N7N',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkK5pJdqplCilV8Z0qCRk7lPRXFwMqmBA',
    appId: '1:232894128071:ios:beea70cf8e7700089243e2',
    messagingSenderId: '232894128071',
    projectId: 'myapp-afa3a',
    storageBucket: 'myapp-afa3a.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSTyYVr9OHo7btLXyDRgu5CcbsZ3b24JA',
    appId: '1:232894128071:web:0ef08e62a58b41b89243e2',
    messagingSenderId: '232894128071',
    projectId: 'myapp-afa3a',
    authDomain: 'myapp-afa3a.firebaseapp.com',
    storageBucket: 'myapp-afa3a.firebasestorage.app',
    measurementId: 'G-Y72LBX6P1J',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkK5pJdqplCilV8Z0qCRk7lPRXFwMqmBA',
    appId: '1:232894128071:ios:beea70cf8e7700089243e2',
    messagingSenderId: '232894128071',
    projectId: 'myapp-afa3a',
    storageBucket: 'myapp-afa3a.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6QG1kBYNsriM8TL2Z4cOn9q8hS7B4iP0',
    appId: '1:232894128071:android:32134529c937d2299243e2',
    messagingSenderId: '232894128071',
    projectId: 'myapp-afa3a',
    storageBucket: 'myapp-afa3a.firebasestorage.app',
  );

}